server:
  port: 8081
spring:
  datasource:
    username: root
    password: admin123
    url: jdbc:mysql://localhost:3309/khoaluan
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-circular-references: true
jwt:
  privateKey: UvmX3g7ww8TZ/PNE+GdL/HaQPlOGs0V3pCoGpB8hxkE=

