server:
  port: 8081
spring:
  datasource:
    username: root
    password: admin123
    url: jdbc:mysql://localhost:3309/khoaluan
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      file-size-threshold: 30MB
      resolve-lazily: true
jwt:
  privateKey: UvmX3g7ww8TZ/PNE+GdL/HaQPlOGs0V3pCoGpB8hxkE=
root:
  path:
    upload: D:\upload\image
logging:
  file:
    name: D:\front-end\khoaluan\backend-web-day-hoc\log\logger.log
  logback:
    rollingpolicy:
      max-file-size: 200MB
redis:
  host: localhost
  port: 6380