server:
  port: 8081
spring:
  datasource:
    username: root
    password: admin123
    url: jdbc:mysql://localhost:3309/khoaluan
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  privateKey: UvmX3g7ww8TZ/PNE+GdL/HaQPlOGs0V3pCoGpB8hxkE=
root:
  path:
    upload: D:\front-end\backend-khoa-luan\upload\image
logging:
  file:
    name: D:\front-end\backend-khoa-luan\log\logger.log
  logback:
    rollingpolicy:
      max-file-size: 200MB
