server:
  port: 8081
spring:
  datasource:
    username: root
    password: admin123
    url: jdbc:mysql://localhost:3309/khoaluan
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      file-size-threshold: 2KB
      resolve-lazily: true
  mail:
    host: smtp.gmail.com
    password: rgxcdilbyklxmisv
    username: dvh31502@gmail.com
    port: 587
jwt:
  privateKey: UvmX3g7ww8TZ/PNE+GdL/HaQPlOGs0V3pCoGpB8hxkE=
root:
  path:
    image: images
    video: videos/
logging:
  file:
    name: D:\front-end\khoaluan\backend-web-day-hoc\log\logger.log
  logback:
    rollingpolicy:
      max-file-size: 200MB
redis:
  host: localhost
  port: 6380