server:
  port: ${PORT}
spring:
  datasource:
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    url: ${URL_DB}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB
      file-size-threshold: 2KB
      resolve-lazily: true
  mail:
    host: ${HOST_MAIL}
    password: ${PASSWORD_MAIL}
    username: ${USERNAME_MAIL}
    port: ${PORT_MAIL}
jwt:
  privateKey: ${PRIVATE_KEY}
root:
  path:
    image: images
    video: videos/
  frontend:
    url: ${FRONTEND_URL}
  vnpay:
    key: ${SECRET_KEY_VNPAY}
    tmn-code: ${TMN_CODE_VNPAY}
    url-return: ${URL_RETURN_VNPAY}
    pay-url: ${PAY_URL}
    api-pay-url: ${API-PAY_URL}
  cloud:
    name: ${CLOUD_NAME}
    key: ${CLOUD_API_KEY}
    secret: ${CLOUD_API_SECRET}
logging:
  file:
    name: D:\front-end\khoaluan\backend-web-day-hoc\log\logger.log
  logback:
    rollingpolicy:
      max-file-size: 200MB
redis:
  host: localhost
  port: 6380