server:
  port: ${PORT}
spring:
  datasource:
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    url: ${URL_DB}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      file-size-threshold: 2KB
      resolve-lazily: true
  mail:
    host: ${HOST_MAIL}
    password: ${PASSWORD_MAIL}
    username: ${USERNAME_MAIL}
    port: ${PORT_MAIL}
jwt:
  privateKey: ${PRIVATE_KEY}
root:
  path:
    image: images
    video: videos/
logging:
  file:
    name: D:\front-end\khoaluan\backend-web-day-hoc\log\logger.log
  logback:
    rollingpolicy:
      max-file-size: 200MB
redis:
  host: localhost
  port: 6380